OOP school library: unit tests
nwakauc/OOP-School-library pull request #7
Opened 2023-04-19 18:01 UTC by uchexm

## In this Milestone we implemented the following ✔;

- Installed `Rspec`;
- Added unit tests for all the methods in all the classes:
- `Book`
- `Person`
- `Student`
- `Teacher`
- `Classroom`
- `Rental`
- **Thank you for reviewing our code 😎.**

2023-04-19 18:55 UTC, Whoistolu requested changes
Hi Team,

@uchexm and @Shakir-Hussain12 
Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

## N/A

Cheers, and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-19 18:55 UTC, Whoistolu commented on spec/book_spec.rb
> +end
- [ ] [REQUIRED] You have done a god job testing the `initialize` method, however, a part of the project requirement stated that you should have unit tests for all the methods in the classes. Kindly add a test for the ` add_rental` method.

2023-04-19 18:55 UTC, Whoistolu commented on spec/person_spec.rb
> +end
- [ ] [REQUIRED] Hello team, it looks like we also forgot to test this private method `of_age?` for the Person class as well. This is a hard requirement so let's fix it 💪🏽

2023-04-19 18:55 UTC, Whoistolu commented on spec/student_spec.rb
> +end
- [ ] [REQUIRED] Great job team, however, in the Student class we need to test for the `add_classroom`, and `play_hooky` methods respectively as stated by the project requirement.

2023-04-20 00:08 UTC, Omar-Muhamad approved these changes
# Approved ✔
### Hi Team,

#### Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

### Congratulations! 🎉 

![giphy (1)](https://user-images.githubusercontent.com/68796232/223283296-e4ee61b3-5609-4707-a1c7-5a3da02d5db9.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-04-20 00:11 UTC, merged